### ISSUE TITLE
Add some test

### ISSUE THREAD

**Issue by kemingy** [kemingy/flaskerk#15]
Currently, this project is tested with examples. Of course, this is not a suitable way.

Here is the list that should be tested:

- [x] `flaskerk.utils.parse_url` for every converter with and without args
- [ ] `flaskerk.exception.HTTPException` default and customized exceptions
- [ ] Query, Data, Response, Exception in `flaskerk.base.Flaskerk.validate`
- [ ] change default config for `flaskerk.base.Flaskerk`

**Comment by mtizima** [comment]
I can implement it

**Comment by mtizima** [comment]
I will continue to pursue this task

**Comment by kemingy** [comment]
Thanks for your contribution.

**Comment by kemingy** [comment]
Closing this issue since all the features are supported by [spectree](https://github.com/0b01001001/spectree). This library may be archived in the future.
