### ISSUE TITLE
same route with multiple methods are not display in swagger

### ISSUE THREAD

**Issue by stanep** [kemingy/flaskerk#19]
Hi I was playing around with flaskerk and found if you have a method
@app.route('/cars', methods=['GET'])
@api.validate(resp=Cars)
def get_cars() -> Cars:
    # return Car(**cars[0])
    # return {'data': [Car(**x).to_json() for x in cars]}
    # return Cars(cars=[Car(**x) for x in cars])
    # return cars
    return Cars(cars=cars)

@app.route('/cars', methods=['POST'])
@api.validate(resp=Car, data=Car)
def post_cars() -> Car:
    data = request.json_data
    return Car(name=data.name, price=data.price, desc=data.desc)

in swagger will display only one (last one) , I fix in the code in base.py in line 103 or 104
instead of just 
routes = {}
I put this
if path not in routes.keys():
     routes[path] = {}

and it worked

**Comment by kemingy** [comment]
Thanks. I made a PR #20 to fix it.
